[code-block-style]
style = "fenced"

[code-fence-style]
style = "backtick"

[emphasis-style]
style = "underscore"

[MD040]
# [fenced-code-language]
allowed-languages = [
  "goat",
  "mermaid",
  "abap",
  "abnf",
  "as",
  "actionscript",
  "as3",
  "actionscript3",
  "ada",
  "ada95",
  "ada2005",
  "agda",
  "al",
  "alloy",
  "ng2",
  "antlr",
  "apacheconf",
  "aconf",
  "apache",
  "apl",
  "applescript",
  "aql",
  "arduino",
  "armasm",
  "autohotkey",
  "ahk",
  "autoit",
  "awk",
  "gawk",
  "mawk",
  "nawk",
  "ballerina",
  "bash",
  "sh",
  "ksh",
  "zsh",
  "shell",
  "bash-session",
  "console",
  "shell-session",
  "bat",
  "batch",
  "dosbatch",
  "winbatch",
  "bib",
  "bibtex",
  "bicep",
  "blitzbasic",
  "b3d",
  "bplus",
  "bnf",
  "bqn",
  "brainfuck",
  "bf",
  "c",
  "csharp",
  "c#",
  "cpp",
  "c++",
  "caddyfile",
  "caddy",
  "caddyfile-directives",
  "caddyfile-d",
  "caddy-d",
  "capnp",
  "cassandra",
  "cql",
  "ceylon",
  "cfengine3",
  "cf3",
  "cfs",
  "chai",
  "chaiscript",
  "chapel",
  "chpl",
  "cheetah",
  "spitfire",
  "clojure",
  "clj",
  "edn",
  "cmake",
  "cobol",
  "coffee-script",
  "coffeescript",
  "coffee",
  "common-lisp",
  "cl",
  "lisp",
  "coq",
  "cr",
  "crystal",
  "css",
  "cue",
  "cython",
  "pyx",
  "pyrex",
  "d",
  "dart",
  "dax",
  "desktop",
  "desktop_entry",
  "diff",
  "udiff",
  "django",
  "jinja",
  "zone",
  "bind",
  "docker",
  "dockerfile",
  "dtd",
  "dylan",
  "ebnf",
  "elixir",
  "ex",
  "exs",
  "elm",
  "emacs",
  "elisp",
  "emacs-lisp",
  "erlang",
  "factor",
  "fennel",
  "fnl",
  "fish",
  "fishshell",
  "forth",
  "fortran",
  "f90",
  "fortranfixed",
  "fsharp",
  "gas",
  "asm",
  "gdscript",
  "gd",
  "gdscript3",
  "gd3",
  "genshi",
  "kid",
  "xml+genshi",
  "xml+kid",
  "html+genshi",
  "html+kid",
  "genshitext",
  "cucumber,",
  "gherkin,",
  "glsl",
  "gnuplot",
  "go",
  "golang",
  "go-html-template",
  "go-template",
  "go-text-template",
  "graphql",
  "graphqls",
  "gql",
  "groff",
  "nroff",
  "man",
  "groovy",
  "handlebars",
  "hbs",
  "hare",
  "haskell",
  "hs",
  "hx",
  "haxe",
  "hxsl",
  "hcl",
  "hexdump",
  "hlb",
  "hlsl",
  "holyc",
  "html",
  "http",
  "hylang",
  "idris",
  "idr",
  "igor",
  "igorpro",
  "ini",
  "cfg",
  "dosini",
  "io",
  "iscdhcpd",
  "j",
  "java",
  "js",
  "javascript",
  "json",
  "julia",
  "jl",
  "jungle",
  "kotlin",
  "lighty",
  "lighttpd",
  "llvm",
  "lua",
  "make",
  "makefile",
  "mf",
  "bsdmake",
  "mako",
  "md",
  "mkd",
  "mason",
  "materialize",
  "mzsql",
  "mathematica",
  "mma",
  "nb",
  "matlab",
  "mcfunction",
  "meson",
  "meson.build",
  "metal",
  "minizinc,",
  "mzn",
  "mlir",
  "modula2",
  "m2",
  "monkeyc",
  "morrowind",
  "mwscript",
  "myghty",
  "mysql",
  "mariadb",
  "nasm",
  "natural",
  "ndisasm",
  "newspeak",
  "nginx",
  "nim",
  "nimrod",
  "nixos",
  "nix",
  "objective-c",
  "objectivec",
  "obj-c",
  "objc",
  "objectpascal",
  "ocaml",
  "octave",
  "odin",
  "ones",
  "onesenterprise,,",
  "openedge",
  "abl",
  "progress",
  "openedgeabl",
  "openscad",
  "org",
  "orgmode",
  "pacmanconf",
  "perl",
  "pl",
  "php",
  "php3",
  "php4",
  "php5",
  "phtml",
  "pig",
  "pkgconfig",
  "plpgsql",
  "text",
  "plain",
  "no-highlight",
  "plutus-core",
  "plc",
  "pony",
  "postgresql",
  "postgres",
  "postscript",
  "postscr",
  "pov",
  "powerquery",
  "pq",
  "powershell",
  "posh",
  "ps1",
  "psm1",
  "psd1",
  "pwsh",
  "prolog",
  "promela",
  "promql",
  "java-properties",
  "protobuf",
  "proto",
  "prql",
  "psl",
  "puppet",
  "python",
  "py",
  "sage",
  "python3",
  "py3",
  "python2",
  "py2",
  "qbasic",
  "basic",
  "qml",
  "qbs",
  "splus",
  "s",
  "r",
  "racket",
  "rkt",
  "ragel",
  "perl6",
  "pl6",
  "raku",
  "jsx",
  "react",
  "reason",
  "reasonml",
  "registry",
  "rego",
  "rst",
  "rest",
  "restructuredtext",
  "rexx",
  "arexx",
  "spec",
  "rb",
  "ruby",
  "duby",
  "rust",
  "rs",
  "sas",
  "sass",
  "scala",
  "scheme",
  "scm",
  "scilab",
  "scss",
  "sed",
  "gsed",
  "ssed",
  "sieve",
  "smali",
  "smalltalk",
  "squeak",
  "st",
  "smarty",
  "snobol",
  "sol",
  "solidity",
  "sp",
  "sparql",
  "sql",
  "squidconf",
  "squid.conf",
  "squid",
  "sml",
  "stas",
  "stylus",
  "svelte",
  "swift",
  "systemd",
  "systemverilog",
  "sv",
  "tablegen",
  "tal",
  "uxntal",
  "tasm",
  "tcl",
  "tcsh",
  "csh",
  "termcap",
  "terminfo",
  "terraform",
  "tf",
  "tex",
  "latex",
  "thrift",
  "toml",
  "tradingview",
  "tv",
  "tsql",
  "t-sql",
  "turing",
  "turtle",
  "twig",
  "ts",
  "tsx",
  "typescript",
  "typoscript",
  "typoscriptcssdata",
  "typoscripthtmldata",
  "ucode",
  "v",
  "vlang",
  "vsh",
  "vshell",
  "vala",
  "vapi",
  "vb.net",
  "vbnet",
  "verilog",
  "v",
  "vhdl",
  "vhs",
  "tape",
  "cassette",
  "vim",
  "vue",
  "vuejs",
  "wgsl",
  "whiley",
  "xml",
  "xorg.conf",
  "yaml",
  "yang",
  "z80",
  "zed",
  "zig",
]
unknown-language-action = "error"

[heading-style]
style = "atx"

[hr-style]
style = "---"

[MD013]
# [line-length]
strict = false
reflow = false
reflow-mode = "sentence-per-line"
code-blocks = false

[MD052]
# reference-links-images
shortcut-syntax = true # Enable checking of shortcut references


[link-image-style]
collapsed = false
shortcut = false
url-inline = false

[no-duplicate-heading]
siblings-only = false

[ol-prefix]
style = "ordered"

[proper-names]
code-blocks = false
names = [
  "Cake.Markdownlint",
  "CommonMark",
  "JavaScript",
  "Markdown",
  "markdown-it",
  "markdownlint",
  "Node.js",
]

[strong-style]
style = "asterisk"

[ul-style]
style = "dash"
